language: scala
scala: 2.12.10
jdk: openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.coursier/cache

env:
  global:
    - COURSIER_PROGRESS=0
    - SBT=./sbt
    # ENCRYPTION_PASSWORD
    - secure: "qwktVQKAn3EYy+NdEubhpm1ZWkapO7ShyLk4hxNuXWkcGB8oFqpZOFM/bkuBIZmTpLz5re+9FkWXqOTHszF66RNn5D9LEZOSbEfu4G5GgLioSSuwxcfpdUmlXp/k3b0lp+Tr92MEoJ4MhPksayA7JWiNV91kQovcwRUPlhwXgC6qr0e5JdIiufnL6iFkgL1FlL/yzl3QlNhozB62r7qtc0o9pf4TlF1ckWyCNzU2kwGTJ0/4/7pfsZaq8aRf8IvsylX1vsGq3R784NHkxJPSBKrgke7N9OQIiCkjV+NlN7tjz3oI6SFhPmHN+0YsvgcDM0cLvHsvxPjysHdmCuPiJ3lLA545FW79wqrwaZ/ygRbwFz3SZMoyTQrq3QOTH/Cp9bb41z4suwFFcTYsbf6FlXZtqEoVtzlZDtOzhdq+OOM0Uo1uE9FACFyLzuSrt+3ksXUwXXqf3wL2qsj+2m+M2B3BuwNN/lDHzby0+gY9Ft+jISXp3N+UCelzL5hRcxeYNrstHJCkF0vt/3v1i7uvQ1lTNhpLWOFfIGUTXu8g9m7+u4/x0MYDZ4hao/CW/ar1U4rwIJF9KPBaP2/V/EYgItQy5hQiLB+YtdKpA/Lu9t5Xtvf3JXt/njIzrAuUkX7Sko+JYb1mpQ0otxytZPI2YRhKUtLZRsCZhZqCwn4z+RQ="
    # GITHUB_TOKEN
    - secure: "BiIq8Y4rAdZYSM8IO65R11d8cXFjWTD/5zHdE+UV4pgG+jf6RuC9F8LVn/ztI61cFoCcONSgNq2B2KoVOlS6Co+Ctnb66/kkfFmkBWdkDdNRuaQ8pi6ijwDHM7XTRwV2Q8yDrwU7VBo6aIsMqhmDcyKc0XJB2Qir6sfPtd4sjqFUprn3IbG4y2GuzIC8t4fsuntG/N5XECZQ6AgOXeXUNP6qoCUHFEw4p558HiM9LUSLS9nMOXOPUzeP6wIJZq6BycdbczHmoZJKVM3+1gJbE7OTEuSmpPUpAbO429ZS7IhSzjr3oae+wnujlpNOnjoUWEsVP/On66qsouZ1sjani7SWk3W3jziXPqQ5kUcFzWyzuzcMtEcrwmMjdiUr5x0jusOik7QOkmAoLZEqZNt7eWTaK20Oe5oN5P/uuI0xbExhewpLMlf3TqmtViGsqGq6a2AeZcdQd4Pgm/O/hyclq7nAiX8sPDzALIXWIngwAEbMKJHSV1YHqtZmvjHnZ4sRp1XNAqNwLBrWwmWOwrnJL+Xnf55I17BYwLOTlyJOFr/VV26SJVYR45fProzH5uZBdAHu21mDXNC4eyhM1D+frFrj1a7T68W/eJb/2r56jywoS6/wFGWZZABAPn1Arc6qw9uTYtPW9A+AlM0uO9YE0fbc/UvW0aDvIRJSFj+cM18="
    # GITHUB_ACCESS_TOKEN
    - secure: "M4cElMTzIlxmIQNjcsfCGupVPOBz1ITuNEnKCQhBmUcwuTJYcZraPfX7IFGAvdAsbw9AJJVgZ+/mTtTfKgdp0Jy8bwOhugXg1w39+9p645YM9G5D3D3AEvyTLJBKY/IFPEsgQsAu5lyeGdDQISgcaFbePQRHHvXWsmZUfP0hUYpC5CPRvbgQ/L70JmrL5ppGGcqMxfd6tm1BJwWNBoKosetb0JFhu5pkT06RxYHdREdJy73lWK0vknlN33FAFujm4laAuqwz7rbPjjoD9vTvinSolmVhmRC5V1hKPM/52qlxR5PvxKVbmfh7VRLOO3u9fsq5QJ+l9S+hRI4Z7pXKxeyOM6Vj3PB8nQG62J0zmNLq3YlmCwkDgInpTXrUy8x/Do/HMwXfs5CwwFjD2zD15kPwxx6XDBVk5Mxgeg3CCGB+GCnoREgTBXNaNFbahSeYFwWDw8vhIypnBppTxjf8LLQL1t275Cc8k+0jdAwjfSNfn2huZceOgUy39QJYdPZD4sXgGsbMmMg2NF5ZESIy888hJ2EDvuuA3zeh/iFwUaklEEh1qR8NXYCF6tg3WgveTyatoBoXbfdLSkRgs2UM8J2+DwM8wdavaWKa35D6dzC16hS9V/P5rb90LroKMkRAXWhiR4gpjomMifA2riAdGDOh2rWlMY+d3BCK4sPeNvQ="
    # DISCORD_WEBHOOK_TOKENS
    - secure: "FGihUO4snpdO8sSwsMoikFOvfvY/bLl5FEyxKqYc1wR6Gwbrq+bmj4Z+Yb6qiIMT0qh0/qJnNu3sutnPfkb+rvE+al1xt0er314SQXMAxy/WCrdjx7XKJclGEJWV+EMIUxRl+IHVtze84n3y0HMzvP3GODkF6ZOFGSpJUioaO1uCoA3YZHsZcslX8+Cjt4av3/auI5J9ZmFQZIhxwQxIGivOwpGokGn9fTXEbv4+1mM96JXlxhj80qk4nRPTA6sw36UzcolFsziMHWdDvlYjhjTSz3bb4rvZB0f1pq8zCuQTFBTe099eR2iGAvXda/yZDO5tQF9o9d9CZi9YYh5NgwrzTcaevfh4gnP2/Vpq7jM4F4CaH7OZnfzoS8RcBLHDSgIxZOXtSQqWdumaI/TMGQQlsg1a6bmcD3Xc8ZSKcmuY2Hy6PKc3gjGAAO5uuMhrWokAZynFTo+DHzpXOmwK/mRt9iHrMP8AxE6KqgB8M6Va5lk/WJJAMX03yOsyRCPMVheVtddtePWi/AvZ+cR4k9LchWddtm4AyBQ1lncbk8+f1jmOW7K5/oMEnxbGzjW4Y1uasyT1jR0Pgnt9EC/AU3rlmY+M5WtF+sQ2YtlIas4+Z89AnMI8khMnohsZi99jGRyf8fMj1SX/Vw58ztwB/yJpb+v/078xm8/fxPSJKNI="

install:
  - mkdir scripts
  - $SBT transferCommonResources
  - scripts/commonSetup

script:
    - set -e

    - $SBT ++$TRAVIS_SCALA_VERSION test

    - |-
      if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_BRANCH" =~ backport/v.*|master ]]; then
        $SBT transferPublishAndTagResources;
        TRAVIS_JOB_NUMBER=1 scripts/publishAndTag 'slamdata/fs2-job';
      fi

after_success:
  - scripts/checkAndAutoMerge
  - scripts/discordTravisPost success https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

after_failure:
  - scripts/discordTravisPost failure https://discordapp.com/api/webhooks/$DISCORD_WEBHOOK_TOKENS

branches:
  only:
    - master
    - /^backport.*$/
